spring:
  # 데이터베이스 연결 설정
  datasource: # 여러 DBaaS에서 가져오기
    url: ${DATABASE_URL} # 데이터베이스 URL
    username: ${DATABASE_USERNAME} # 데이터베이스 사용자 이름
    password: ${DATABASE_PASSWORD} # 데이터베이스 비밀번호
    driver-class-name: ${DATABASE_DRIVER} # PostgreSQL 드라이버 클래스 이름

  security:
    user:
      name: ${SECURITY_NAME}
      password: ${SECURITY_PASSWORD}